# Generated by Django 3.2.18 on 2023-05-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Объявление',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('товар', models.CharField(max_length=200)),
                ('фото', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('описание_товара', models.TextField()),
                ('цена', models.FloatField(blank=True)),
                ('дата', models.DateTimeField(auto_now_add=True)),
                ('телефон', models.CharField(max_length=20)),
                ('адрес', models.CharField(max_length=200)),
                ('категория', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning_logs.категория')),
            ],
            options={
                'verbose_name_plural': 'Объявлении',
                'ordering': ['-дата'],
            },
        ),
    ]
