# Generated by Django 3.2.18 on 2023-05-03 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0002_объявление'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='объявление',
            options={'ordering': ['-дата'], 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='объявление',
            name='wner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
