# Generated by Django 3.2.18 on 2023-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_alter_объявление_wner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='категория',
            name='категория',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='объявление',
            name='адрес',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='объявление',
            name='описание_товара',
            field=models.TextField(max_length=300),
        ),
    ]
