# Generated by Django 3.2.18 on 2023-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_auto_20230508_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='объявление',
            name='число',
            field=models.IntegerField(null=True),
        ),
    ]
